"""Renders a ProtocolSpec into a standalone Python connector module.

Each generated module exposes a single `parse(...)` function and depends
only on canonical.py and the stdlib — it has no runtime dependency on the
generator or on PyYAML, so it can be committed and shipped independently of
the tool that produced it.
"""

from __future__ import annotations

from generator.spec import FieldSpec, ProtocolSpec

_HEADER = '''\
"""Generated connector for {protocol} / {message_id} — DO NOT EDIT BY HAND.

Generated by generator.codegen from a declarative ProtocolSpec.
Regenerate with: python -m generator.cli generate --spec <spec.yaml> --out <this file>
"""

from __future__ import annotations

'''


def generate(spec: ProtocolSpec) -> str:
    if spec.transport == "delimited_text":
        return _generate_delimited_text(spec)
    if spec.transport == "register_map":
        return _generate_register_map(spec)
    raise ValueError(f"no codegen backend for transport {spec.transport!r}")


# ---------------------------------------------------------------------------
# delimited_text backend (e.g. ASCII sensor telemetry sentences)
# ---------------------------------------------------------------------------

def _generate_delimited_text(spec: ProtocolSpec) -> str:
    max_index = max(f.index for f in spec.fields)

    ts_field = (
        spec.field_by_name(spec.canonical.timestamp_field)
        if spec.canonical.timestamp_field
        else None
    )
    needs_reference_date = bool(
        ts_field and ts_field.type == "hms_time" and not spec.canonical.date_field
    )

    used_helpers = {"_checksum_ok"}
    if ts_field and ts_field.type == "hms_time":
        used_helpers.add("_ddmmyy_hms_to_iso" if spec.canonical.date_field else "_hms_time_to_iso")
    if spec.canonical.location:
        used_helpers.add("_dm_coord_to_decimal")

    lines: list[str] = []
    lines.append(_HEADER.format(protocol=spec.protocol, message_id=spec.message.id))
    lines.append("import datetime as _dt\n")
    lines.append("from canonical import CanonicalReading, Location, Measurement\n\n")
    lines.append(f'PROTOCOL = "{spec.protocol}"')
    lines.append(f'MESSAGE_TYPE = "{spec.message.id}"')
    lines.append(f'MATCH_SUFFIX = "{spec.message.match_suffix}"')
    lines.append("")
    _emit_helpers(lines, _DELIMITED_TEXT_HELPERS, used_helpers)

    lines.append("def parse(")
    lines.append("    sentence: str,")
    lines.append("    device_id: str,")
    if needs_reference_date:
        lines.append("    reference_date: _dt.date | None = None,")
    lines.append(") -> CanonicalReading | None:")
    lines.append(f'    """Parse one {spec.message.id} sentence into a CanonicalReading."""')
    lines.append("    sentence = sentence.strip()")
    lines.append("    if not _checksum_ok(sentence):")
    lines.append("        return None")
    lines.append("")
    lines.append(f'    parts = sentence.split("*")[0].split("{spec.delimiter}")')
    lines.append(f"    if len(parts) < {max_index + 1}:")
    lines.append("        return None")
    lines.append(
        "    if len(parts[0]) < len(MATCH_SUFFIX) or parts[0][-len(MATCH_SUFFIX):] != MATCH_SUFFIX:"
    )
    lines.append("        return None")
    lines.append("")

    special_types = {"hms_time", "ddmmyy_date", "dm_lat", "dm_lon"}
    for f in spec.fields:
        lines.append("    " + _field_extraction_line(f))

    lines.append("")
    if needs_reference_date:
        lines.append("    reference_date = reference_date or _dt.datetime.now(_dt.timezone.utc).date()")
        lines.append("")

    if ts_field:
        if ts_field.type == "hms_time":
            if spec.canonical.date_field:
                date_field = spec.field_by_name(spec.canonical.date_field)
                lines.append(
                    f"    timestamp = _ddmmyy_hms_to_iso({date_field.name}_raw, {ts_field.name}_raw)"
                )
            else:
                lines.append(f"    timestamp = _hms_time_to_iso({ts_field.name}_raw, reference_date)")
        else:
            lines.append(f"    timestamp = str({ts_field.name})")
    else:
        lines.append('    timestamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")')

    if spec.canonical.location:
        loc = spec.canonical.location
        lat_field = spec.field_by_name(loc.lat_field)
        lon_field = spec.field_by_name(loc.lon_field)
        lines.append(
            f"    lat = _dm_coord_to_decimal({lat_field.name}_raw, {loc.lat_dir_field}, degree_digits=2)"
        )
        lines.append(
            f"    lon = _dm_coord_to_decimal({lon_field.name}_raw, {loc.lon_dir_field}, degree_digits=3)"
        )
        lines.append("    location = Location(lat=lat, lon=lon)")
    else:
        lines.append("    location = None")

    lines.append("")
    lines.append("    measurements = [")
    for m in spec.canonical.measurements:
        unit_repr = f'"{m.unit}"' if m.unit else "None"
        lines.append(f'        Measurement(name="{m.name}", value={m.field}, unit={unit_repr}),')
    lines.append("    ]")
    lines.append("")

    lines.append("    raw = {")
    for f in spec.fields:
        var = f"{f.name}_raw" if f.type in special_types else f.name
        lines.append(f'        "{f.name}": {var},')
    lines.append("    }")
    lines.append("")

    lines.append("    return CanonicalReading(")
    lines.append("        device_id=device_id,")
    lines.append("        protocol=PROTOCOL,")
    lines.append("        message_type=MESSAGE_TYPE,")
    lines.append("        timestamp=timestamp,")
    lines.append("        measurements=measurements,")
    lines.append("        location=location,")
    lines.append("        raw=raw,")
    lines.append("    )")
    lines.append("")

    return "\n".join(lines)


def _field_extraction_line(f: FieldSpec) -> str:
    idx = f.index
    if f.type == "str":
        return f"{f.name} = parts[{idx}]"
    if f.type == "int":
        return f"{f.name} = int(parts[{idx}]) if parts[{idx}] else None"
    if f.type == "float":
        return f"{f.name} = float(parts[{idx}]) if parts[{idx}] else None"
    if f.type in ("hms_time", "ddmmyy_date", "dm_lat", "dm_lon"):
        return f"{f.name}_raw = parts[{idx}]"
    raise ValueError(f"unhandled delimited_text field type {f.type!r}")


_DELIMITED_TEXT_HELPERS = '''\
def _checksum_ok(sentence: str) -> bool:
    if "*" not in sentence:
        return False
    body, _, checksum = sentence.partition("*")
    body = body.lstrip("$")
    calc = 0
    for ch in body:
        calc ^= ord(ch)
    try:
        return calc == int(checksum.strip(), 16)
    except ValueError:
        return False


def _hms_time_to_iso(raw: str, reference_date: _dt.date) -> str:
    raw = raw.split(".")[0]
    hh, mm, ss = int(raw[0:2]), int(raw[2:4]), int(raw[4:6])
    dt = _dt.datetime(
        reference_date.year, reference_date.month, reference_date.day,
        hh, mm, ss, tzinfo=_dt.timezone.utc,
    )
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _ddmmyy_hms_to_iso(date_raw: str, time_raw: str) -> str:
    # ddmmyy dates use a 2-digit year; assumed 2000-2099. This is a known
    # limitation of that date encoding itself, not this parser.
    dd, mm, yy = int(date_raw[0:2]), int(date_raw[2:4]), int(date_raw[4:6])
    time_raw = time_raw.split(".")[0]
    hh, mi, ss = int(time_raw[0:2]), int(time_raw[2:4]), int(time_raw[4:6])
    dt = _dt.datetime(2000 + yy, mm, dd, hh, mi, ss, tzinfo=_dt.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _dm_coord_to_decimal(raw: str, direction: str, degree_digits: int) -> float:
    degrees = int(raw[:degree_digits])
    minutes = float(raw[degree_digits:])
    decimal = degrees + minutes / 60.0
    if direction in ("S", "W"):
        decimal = -decimal
    return decimal


'''


# ---------------------------------------------------------------------------
# register_map backend (e.g. Modbus)
# ---------------------------------------------------------------------------

_REGISTER_DECODERS = {
    "uint16": "_decode_uint16",
    "int16": "_decode_int16",
    "uint32": "_decode_uint32",
    "int32": "_decode_int32",
}

_REGISTER_HELPERS = '''\
def _decode_uint16(raw: int) -> int:
    return raw & 0xFFFF


def _decode_int16(raw: int) -> int:
    raw &= 0xFFFF
    return raw - 0x10000 if raw & 0x8000 else raw


def _decode_uint32(lo_raw: int, hi_raw: int) -> int:
    # Assumes low word at `address`, high word at `address + 1`.
    return ((hi_raw & 0xFFFF) << 16) | (lo_raw & 0xFFFF)


def _decode_int32(lo_raw: int, hi_raw: int) -> int:
    value = _decode_uint32(lo_raw, hi_raw)
    return value - 0x100000000 if value & 0x80000000 else value


'''


def _generate_register_map(spec: ProtocolSpec) -> str:
    lines: list[str] = []
    lines.append(_HEADER.format(protocol=spec.protocol, message_id=spec.message.id))
    lines.append("from canonical import CanonicalReading, Measurement\n\n")
    lines.append(f'PROTOCOL = "{spec.protocol}"')
    lines.append(f'MESSAGE_TYPE = "{spec.message.id}"')
    lines.append("")

    used_decoders = {_REGISTER_DECODERS[f.type] for f in spec.fields}
    _emit_helpers(lines, _REGISTER_HELPERS, used_decoders)

    lines.append("def parse(")
    lines.append("    registers: dict[int, int],")
    lines.append("    device_id: str,")
    lines.append("    timestamp: str,")
    lines.append(") -> CanonicalReading | None:")
    lines.append(f'    """Parse {spec.message.id} holding registers into a CanonicalReading."""')
    lines.append("    try:")
    for f in spec.fields:
        if f.type in ("uint32", "int32"):
            lines.append(f"        {f.name}_raw = (registers[{f.address}], registers[{f.address + 1}])")
        else:
            lines.append(f"        {f.name}_raw = registers[{f.address}]")
    lines.append("    except KeyError:")
    lines.append("        return None")
    lines.append("")

    for f in spec.fields:
        decoder = _REGISTER_DECODERS[f.type]
        if f.type in ("uint32", "int32"):
            decoded = f"{decoder}(*{f.name}_raw)"
        else:
            decoded = f"{decoder}({f.name}_raw)"
        if f.scale != 1.0:
            lines.append(f"    {f.name} = {decoded} * {f.scale}")
        else:
            lines.append(f"    {f.name} = {decoded}")

    lines.append("")
    lines.append("    measurements = [")
    for m in spec.canonical.measurements:
        unit_repr = f'"{m.unit}"' if m.unit else "None"
        lines.append(f'        Measurement(name="{m.name}", value={m.field}, unit={unit_repr}),')
    lines.append("    ]")
    lines.append("")

    lines.append("    raw = {")
    for f in spec.fields:
        lines.append(f'        "{f.name}": {f.name}_raw,')
    lines.append("    }")
    lines.append("")

    lines.append("    return CanonicalReading(")
    lines.append("        device_id=device_id,")
    lines.append("        protocol=PROTOCOL,")
    lines.append("        message_type=MESSAGE_TYPE,")
    lines.append("        timestamp=timestamp,")
    lines.append("        measurements=measurements,")
    lines.append("        location=None,")
    lines.append("        raw=raw,")
    lines.append("    )")
    lines.append("")

    return "\n".join(lines)


def _split_helpers(block: str) -> list[tuple[str, str]]:
    """Split a block of top-level function defs into (name, source) pairs.

    Each source is rstripped so callers can join a chosen subset with
    consistent spacing regardless of which helpers were filtered out.
    """
    chunks: list[tuple[str, str]] = []
    current: list[str] = []
    current_name: str | None = None
    for line in block.splitlines(keepends=True):
        if line.startswith("def "):
            if current_name is not None:
                chunks.append((current_name, "".join(current).rstrip("\n")))
            current_name = line[len("def "):].split("(")[0]
            current = [line]
        else:
            current.append(line)
    if current_name is not None:
        chunks.append((current_name, "".join(current).rstrip("\n")))
    return chunks


def _emit_helpers(lines: list[str], block: str, wanted: set[str]) -> None:
    """Append the chunks of `block` whose name is in `wanted`, evenly spaced."""
    selected = [src for name, src in _split_helpers(block) if name in wanted]
    if selected:
        lines.append("\n\n\n".join(selected))
        lines.append("")
