"""Generated connector for modbus_plc / line_telemetry — DO NOT EDIT BY HAND.

Generated by generator.codegen from a declarative ProtocolSpec.
Regenerate with: python -m generator.cli generate --spec <spec.yaml> --out <this file>
"""

from __future__ import annotations


from canonical import CanonicalReading, Measurement


PROTOCOL = "modbus_plc"
MESSAGE_TYPE = "line_telemetry"

def _decode_uint16(raw: int) -> int:
    return raw & 0xFFFF


def _decode_int16(raw: int) -> int:
    raw &= 0xFFFF
    return raw - 0x10000 if raw & 0x8000 else raw


def _decode_uint32(lo_raw: int, hi_raw: int) -> int:
    # Assumes low word at `address`, high word at `address + 1`.
    return ((hi_raw & 0xFFFF) << 16) | (lo_raw & 0xFFFF)

def parse(
    registers: dict[int, int],
    device_id: str,
    timestamp: str,
) -> CanonicalReading | None:
    """Parse line_telemetry holding registers into a CanonicalReading."""
    try:
        line_speed_upm_raw = registers[0]
        motor_current_a_raw = registers[1]
        motor_temp_c_raw = registers[2]
        uptime_hours_raw = (registers[3], registers[4])
    except KeyError:
        return None

    line_speed_upm = _decode_uint16(line_speed_upm_raw)
    motor_current_a = _decode_uint16(motor_current_a_raw) * 0.1
    motor_temp_c = _decode_int16(motor_temp_c_raw) * 0.1
    uptime_hours = _decode_uint32(*uptime_hours_raw) * 0.1

    measurements = [
        Measurement(name="line_speed_upm", value=line_speed_upm, unit="units_per_min"),
        Measurement(name="motor_current_a", value=motor_current_a, unit="amps"),
        Measurement(name="motor_temp_c", value=motor_temp_c, unit="celsius"),
        Measurement(name="uptime_hours", value=uptime_hours, unit="hours"),
    ]

    raw = {
        "line_speed_upm": line_speed_upm_raw,
        "motor_current_a": motor_current_a_raw,
        "motor_temp_c": motor_temp_c_raw,
        "uptime_hours": uptime_hours_raw,
    }

    return CanonicalReading(
        device_id=device_id,
        protocol=PROTOCOL,
        message_type=MESSAGE_TYPE,
        timestamp=timestamp,
        measurements=measurements,
        location=None,
        raw=raw,
    )
