"""Generated connector for industrial_ascii / PROC — DO NOT EDIT BY HAND.

Generated by generator.codegen from a declarative ProtocolSpec.
Regenerate with: python -m generator.cli generate --spec <spec.yaml> --out <this file>
"""

from __future__ import annotations


import datetime as _dt

from canonical import CanonicalReading, Location, Measurement


PROTOCOL = "industrial_ascii"
MESSAGE_TYPE = "PROC"
MATCH_SUFFIX = "PROC"

def _checksum_ok(sentence: str) -> bool:
    if "*" not in sentence:
        return False
    body, _, checksum = sentence.partition("*")
    body = body.lstrip("$")
    calc = 0
    for ch in body:
        calc ^= ord(ch)
    try:
        return calc == int(checksum.strip(), 16)
    except ValueError:
        return False


def _hms_time_to_iso(raw: str, reference_date: _dt.date) -> str:
    raw = raw.split(".")[0]
    hh, mm, ss = int(raw[0:2]), int(raw[2:4]), int(raw[4:6])
    dt = _dt.datetime(
        reference_date.year, reference_date.month, reference_date.day,
        hh, mm, ss, tzinfo=_dt.timezone.utc,
    )
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _dm_coord_to_decimal(raw: str, direction: str, degree_digits: int) -> float:
    degrees = int(raw[:degree_digits])
    minutes = float(raw[degree_digits:])
    decimal = degrees + minutes / 60.0
    if direction in ("S", "W"):
        decimal = -decimal
    return decimal

def parse(
    sentence: str,
    device_id: str,
    reference_date: _dt.date | None = None,
) -> CanonicalReading | None:
    """Parse one PROC sentence into a CanonicalReading."""
    sentence = sentence.strip()
    if not _checksum_ok(sentence):
        return None

    parts = sentence.split("*")[0].split(",")
    if len(parts) < 10:
        return None
    if len(parts[0]) < len(MATCH_SUFFIX) or parts[0][-len(MATCH_SUFFIX):] != MATCH_SUFFIX:
        return None

    reading_time_raw = parts[1]
    site_lat_raw = parts[2]
    site_lat_dir = parts[3]
    site_lon_raw = parts[4]
    site_lon_dir = parts[5]
    sensor_status = int(parts[6]) if parts[6] else None
    temperature_c = float(parts[7]) if parts[7] else None
    pressure_bar = float(parts[8]) if parts[8] else None
    flow_rate_m3h = float(parts[9]) if parts[9] else None

    reference_date = reference_date or _dt.datetime.now(_dt.timezone.utc).date()

    timestamp = _hms_time_to_iso(reading_time_raw, reference_date)
    lat = _dm_coord_to_decimal(site_lat_raw, site_lat_dir, degree_digits=2)
    lon = _dm_coord_to_decimal(site_lon_raw, site_lon_dir, degree_digits=3)
    location = Location(lat=lat, lon=lon)

    measurements = [
        Measurement(name="sensor_status", value=sensor_status, unit="none"),
        Measurement(name="temperature_c", value=temperature_c, unit="celsius"),
        Measurement(name="pressure_bar", value=pressure_bar, unit="bar"),
        Measurement(name="flow_rate_m3h", value=flow_rate_m3h, unit="m3h"),
    ]

    raw = {
        "reading_time": reading_time_raw,
        "site_lat": site_lat_raw,
        "site_lat_dir": site_lat_dir,
        "site_lon": site_lon_raw,
        "site_lon_dir": site_lon_dir,
        "sensor_status": sensor_status,
        "temperature_c": temperature_c,
        "pressure_bar": pressure_bar,
        "flow_rate_m3h": flow_rate_m3h,
    }

    return CanonicalReading(
        device_id=device_id,
        protocol=PROTOCOL,
        message_type=MESSAGE_TYPE,
        timestamp=timestamp,
        measurements=measurements,
        location=location,
        raw=raw,
    )
