"""Generated connector for wx_ascii / WXOBSF — DO NOT EDIT BY HAND.

Generated by generator.codegen from a declarative ProtocolSpec.
Regenerate with: python -m generator.cli generate --spec <spec.yaml> --out <this file>
"""

from __future__ import annotations


import datetime as _dt

from canonical import CanonicalReading, Location, Measurement


PROTOCOL = "wx_ascii"
MESSAGE_TYPE = "WXOBSF"
MATCH_SUFFIX = "WXOBSF"

def _checksum_ok(sentence: str) -> bool:
    if "*" not in sentence:
        return False
    body, _, checksum = sentence.partition("*")
    body = body.lstrip("$")
    calc = 0
    for ch in body:
        calc ^= ord(ch)
    try:
        return calc == int(checksum.strip(), 16)
    except ValueError:
        return False


def _ddmmyy_hms_to_iso(date_raw: str, time_raw: str) -> str:
    # ddmmyy dates use a 2-digit year; assumed 2000-2099. This is a known
    # limitation of that date encoding itself, not this parser.
    dd, mm, yy = int(date_raw[0:2]), int(date_raw[2:4]), int(date_raw[4:6])
    time_raw = time_raw.split(".")[0]
    hh, mi, ss = int(time_raw[0:2]), int(time_raw[2:4]), int(time_raw[4:6])
    dt = _dt.datetime(2000 + yy, mm, dd, hh, mi, ss, tzinfo=_dt.timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _dm_coord_to_decimal(raw: str, direction: str, degree_digits: int) -> float:
    degrees = int(raw[:degree_digits])
    minutes = float(raw[degree_digits:])
    decimal = degrees + minutes / 60.0
    if direction in ("S", "W"):
        decimal = -decimal
    return decimal

def parse(
    sentence: str,
    device_id: str,
) -> CanonicalReading | None:
    """Parse one WXOBSF sentence into a CanonicalReading."""
    sentence = sentence.strip()
    if not _checksum_ok(sentence):
        return None

    parts = sentence.split("*")[0].split(",")
    if len(parts) < 10:
        return None
    if len(parts[0]) < len(MATCH_SUFFIX) or parts[0][-len(MATCH_SUFFIX):] != MATCH_SUFFIX:
        return None

    obs_time_raw = parts[1]
    status = parts[2]
    site_lat_raw = parts[3]
    site_lat_dir = parts[4]
    site_lon_raw = parts[5]
    site_lon_dir = parts[6]
    wind_speed_kmh = float(parts[7]) if parts[7] else None
    wind_dir_deg = int(parts[8]) if parts[8] else None
    obs_date_raw = parts[9]

    timestamp = _ddmmyy_hms_to_iso(obs_date_raw, obs_time_raw)
    lat = _dm_coord_to_decimal(site_lat_raw, site_lat_dir, degree_digits=2)
    lon = _dm_coord_to_decimal(site_lon_raw, site_lon_dir, degree_digits=3)
    location = Location(lat=lat, lon=lon)

    measurements = [
        Measurement(name="wind_speed_kmh", value=wind_speed_kmh, unit="kmh"),
        Measurement(name="wind_dir_deg", value=wind_dir_deg, unit="degrees"),
    ]

    raw = {
        "obs_time": obs_time_raw,
        "status": status,
        "site_lat": site_lat_raw,
        "site_lat_dir": site_lat_dir,
        "site_lon": site_lon_raw,
        "site_lon_dir": site_lon_dir,
        "wind_speed_kmh": wind_speed_kmh,
        "wind_dir_deg": wind_dir_deg,
        "obs_date": obs_date_raw,
    }

    return CanonicalReading(
        device_id=device_id,
        protocol=PROTOCOL,
        message_type=MESSAGE_TYPE,
        timestamp=timestamp,
        measurements=measurements,
        location=location,
        raw=raw,
    )
