"""Generated connector for modbus_weather / station_telemetry — DO NOT EDIT BY HAND.

Generated by generator.codegen from a declarative ProtocolSpec.
Regenerate with: python -m generator.cli generate --spec <spec.yaml> --out <this file>
"""

from __future__ import annotations


from canonical import CanonicalReading, Measurement


PROTOCOL = "modbus_weather"
MESSAGE_TYPE = "station_telemetry"

def _decode_uint16(raw: int) -> int:
    return raw & 0xFFFF

def parse(
    registers: dict[int, int],
    device_id: str,
    timestamp: str,
) -> CanonicalReading | None:
    """Parse station_telemetry holding registers into a CanonicalReading."""
    try:
        rain_mm_raw = registers[0]
        wind_gust_kmh_raw = registers[1]
        battery_v_raw = registers[2]
        uv_index_raw = registers[3]
    except KeyError:
        return None

    rain_mm = _decode_uint16(rain_mm_raw) * 0.1
    wind_gust_kmh = _decode_uint16(wind_gust_kmh_raw) * 0.1
    battery_v = _decode_uint16(battery_v_raw) * 0.01
    uv_index = _decode_uint16(uv_index_raw) * 0.1

    measurements = [
        Measurement(name="rain_mm", value=rain_mm, unit="mm"),
        Measurement(name="wind_gust_kmh", value=wind_gust_kmh, unit="kmh"),
        Measurement(name="battery_v", value=battery_v, unit="volts"),
        Measurement(name="uv_index", value=uv_index, unit="none"),
    ]

    raw = {
        "rain_mm": rain_mm_raw,
        "wind_gust_kmh": wind_gust_kmh_raw,
        "battery_v": battery_v_raw,
        "uv_index": uv_index_raw,
    }

    return CanonicalReading(
        device_id=device_id,
        protocol=PROTOCOL,
        message_type=MESSAGE_TYPE,
        timestamp=timestamp,
        measurements=measurements,
        location=None,
        raw=raw,
    )
